-- lines
INSERT INTO lines (name, color) VALUES
    ('Crimson Line',  '#C0392B'),
    ('Silver Line',   '#95A5A6'),
    ('Golden Line',   '#F39C12'),
    ('Obsidian Line', '#2C3E50');

-- stations
INSERT INTO stations (name) VALUES
    ('Irongate'),
    ('Ashenveil'),
    ('The Crypt'),
    ('Duskwall'),
    ('Embervane'),
    ('Thornwick'),
    ('Mirefall'),
    ('Stonemarsh'),
    ('Grimholt'),
    ('Cresthold'),
    ('Ravenspire'),
    ('Dawnspire'),
    ('Hollowfen'),
    ('Goldengate');

-- Crimson Line: Irongate(1) ── Ashenveil(2) ── The Crypt(3) ── Duskwall(4) ── Embervane(5)
INSERT INTO line_stations (line_id, station_id, position) VALUES
    (1, 1, 1),
    (1, 2, 2),
    (1, 3, 3),
    (1, 4, 4),
    (1, 5, 5);

-- Silver Line: Thornwick(6) ── Ashenveil(2) ── Mirefall(7) ── Stonemarsh(8) ── Grimholt(9)
INSERT INTO line_stations (line_id, station_id, position) VALUES
    (2, 6, 1),
    (2, 2, 2),
    (2, 7, 3),
    (2, 8, 4),
    (2, 9, 5);

-- Golden Line: Mirefall(7) ── Cresthold(10) ── The Crypt(3) ── Ravenspire(11) ── Dawnspire(12)
INSERT INTO line_stations (line_id, station_id, position) VALUES
    (3, 7, 1),
    (3, 10, 2),
    (3, 3, 3),
    (3, 11, 4),
    (3, 12, 5);

-- Obsidian Line: Stonemarsh(8) ── Ravenspire(11) ── Duskwall(4) ── Hollowfen(13) ── Goldengate(14)
INSERT INTO line_stations (line_id, station_id, position) VALUES
    (4, 8, 1),
    (4, 11, 2),
    (4, 4, 3),
    (4, 13, 4),
    (4, 14, 5);

-- events
INSERT INTO events (description, effect) VALUES
    ('Smooth ride through the ancient tunnels.', 0),
    ('Herald announces your arrival and fellow travelers applaud.', 2),
    ('A pickpocket slips through the crowd.', -2),
    ('Kind merchant shares his lantern and company.', 1),
    ('Wrong platform. You miss your carriage and buy a new ticket.', -1),
    ('A royal decree grants free passage. Conductor refunds your fare.', 3),
    ('Tunnel collapse scare. Emergency evacuation fee charged.', -3),
    ('You find a lost coin purse on the bench', 4),
    ('Rat infestation ruins your provisions.You discard your coin satchel.', -4),
    ('Guard suspects a fugitive. Bribes demanded to pass through.', -1);

-- Users (passwords are bcrypt hashes — generated by init-db.js)

-- Placeholder: actual hashes inserted by the JS seed script